### ISSUE TITLE
Custom ascii work

### ISSUE THREAD

**Issue by eonia89** [MeanderingProgrammer/dashboard.nvim#2]
Hi,

I really like your design and art.
I would like to change the logo with my custom ascii work.
Which part of the code should I modify to load mine?

Thanks!

**Comment by MeanderingProgrammer** [comment]
Hi there,

The header options section goes over that briefly: https://github.com/MeanderingProgrammer/dashboard.nvim?tab=readme-ov-file#header

You would just do something like:

```
require('dashboard').setup({
  header = {
    [[ WHATEVER ]],
    [[ VALUE    ]],
    [[ YOU      ]],
    [[ WANT     ]],
  },
})
```

The ones I use come from the ascii.nvim plugin, can see all the options for neovim text here: https://github.com/MaximilianLloyd/ascii.nvim/blob/master/lua/ascii/text/neovim.lua

The only thing worth noting is that you'll need to provide an array (lua table) of strings as input, instead of just a single string, but other than that you can configure it however you like.

Hope that helps.
